services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: BlitoDB
    ports:
      - "127.0.0.1:6000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: blito-backend
    depends_on:
      - db
    environment:
      SECRET_KEY: your-secret-key
      DEBUG: "True"
    ports:
      - "127.0.0.1:9000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data:
